# Generated by Django 3.0 on 2020-09-17 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseInfo',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)])),
                ('course_code', models.CharField(max_length=10)),
                ('professor', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Course Info',
            },
        ),
    ]
