# Generated by Django 3.0 on 2020-10-05 08:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
                ('major', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Military Science', 'Military Science'), ('Finance', 'Finance'), ('Physics', 'Physics'), ('Biology', 'Biology')], max_length=50)),
                ('eof', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('arc', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Info',
            },
        ),
    ]
